title: Shantanu Mishra
author: Shantanu Mishra

favicon: favicon.svg
remote_theme: yree/mold

footer_content: >
  ##### Â© 2024 [8hantanu](https://8hantanu.net) | [ğŸ“œ disclaimer](disclaimer) | [ğŸ“¬ contact](javascript:window.location='mailto:hey@8hantanu.net?subject='+encodeURIComponent(document.title))
